CREATE TABLE CUSTOMER(

  CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL VARCHAR(64),
  PHONE_NUMBER VARCHAR(64),
  CITY VARCHAR(64)
);

SELECT * FROM CUSTOMER;